In [2]:
import numpy as np

In [3]:
a=[1,2,4,78,9]
type(a)

list

In [4]:
ar=np.array(a)
type(ar)

numpy.ndarray

In [5]:
np.ndim(ar)

1

In [6]:
b=np.array([[1,2,3,4],[3,5,6,7]])
np.ndim(b)

2

In [7]:
b.shape

(2, 4)

In [8]:
b.size

8

In [7]:
import numpy as np 
d = np.array([[[1,2,3],[2,3,4],[3,7,9]]])
np.ndim(d)

3

In [11]:
d[0][2]

array([3, 7, 9])

In [12]:
d.shape

(1, 3, 3)

In [13]:
np.int64(4)

np.int64(4)

In [17]:
v=np.arange(0,100,2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
e=np.linspace(1,5,10)
e

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
d[0][1][1]

np.int64(3)

In [24]:
d.reshape(3,3)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 7, 9]])

In [25]:
d.sum()

np.int64(34)

In [27]:
d.mean()

np.float64(3.7777777777777777)

In [29]:
d.max()

np.int64(9)

In [30]:
d.min()

np.int64(1)

In [31]:
d.std()

np.float64(2.4393887111222385)

In [39]:
np.random.seed(1)
np.random.rand(10)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [40]:
np.random.randint(1,10,5)

array([6, 3, 5, 3, 5], dtype=int32)

In [41]:
d.var()

np.float64(5.950617283950617)

In [42]:
a=np.array([10,20,30,40,50])
a[2]

np.int64(30)

In [43]:
a[0:3]

array([10, 20, 30])

In [45]:
b=np.arange(1,50)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
b[13:17]

array([14, 15, 16, 17])

In [52]:
c=np.array([1,2,3,4,5,6])
c[2:]

array([3, 4, 5, 6])

In [50]:
c[:-1]

array([1, 2, 3, 4, 5])

In [53]:
e=np.array([6,3,9,1,2])
e

array([6, 3, 9, 1, 2])

In [54]:
e[-3]

np.int64(9)

In [55]:
e[:-3]

array([6, 3])

In [56]:
e[1:-3]

array([3])

In [57]:
#filtering

In [58]:
e[e>2]

array([6, 3, 9])

In [66]:
b1=np.arange(1,10)
b2=np.arange(15,25)

In [67]:
print(b1)
print(b2)

[1 2 3 4 5 6 7 8 9]
[15 16 17 18 19 20 21 22 23 24]


In [71]:
np.concatenate((b1,b2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [76]:
np.array_split(b1,2)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [77]:
np.sort(b1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# Assistant
# Option 1: Dot product (if arrays should be same length, trim the longer one)
import numpy as np
min_length = min(len(b1), len(b2))
result = np.dot(b1[:min_length], b2[:min_length])
print(result)

# Option 2: Element-wise multiplication (trim to same length)
# result = b1[:min_length] * b2[:min_length]
# print(result)

# Option 3: Outer product (creates a 9x10 matrix)
# result = np.outer(b1, b2)
# print(result)

# Option 4: If you want to pad the shorter array with zeros
# max_length = max(len(b1), len(b2))
# b1_padded = np.pad(b1, (0, max_length - len(b1)))
# b2_padded = np.pad(b2, (0, max_length - len(b2)))
# result = b1_padded * b2_padded
# print(result)

915


In [84]:
np.dot(b1, b2[:9])

np.int64(915)

In [85]:
a=np.array([[1,2],[3,4]])
b=np.array([[2],[4]])
np.dot(a,b)

array([[10],
       [22]])

In [86]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [89]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])


The corrected code shows the most common solution (dot product with trimmed arrays). Uncomment the other options based on your specific needs. The key change is ensuring both arrays have compatible shapes before performing the multiplication operation.