In [1]:
import numpy as np

In [2]:
#Create a NumPy array with values from 1 to 20

In [3]:
arr = np.arange(1, 21)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
#Create a 5×5 matrix filled with zeros

In [5]:
zeros_matrix = np.zeros((5, 5))
print(zeros_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#Create a 4×4 identity matrix

In [7]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#Generate 15 random integers between 10 and 100

In [9]:
random_numbers = np.random.randint(10, 101, 15)
print(random_numbers)

[64 46 56 94 75 95 16 86 26 34 86 85 72 71 58]


In [10]:
#Find the shape, size, and datatype of an array

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Datatype:", arr.dtype)

Shape: (5,)
Size: 5
Datatype: int64


In [12]:
#Reshape a 1D array of 24 elements into a 4×6 matrix

In [13]:
arr = np.arange(1, 25)
reshaped = arr.reshape(4, 6)
print(reshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [14]:
#Convert a 2D array into a 1D array

In [15]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr_1d = arr_2d.flatten()
print(arr_1d)

[1 2 3 4 5 6]


In [16]:
#Create an array containing only even numbers from 1 to 50

In [17]:
even_numbers = np.arange(2, 51, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [18]:
#Create an array containing multiples of 5 from 0 to 100

In [19]:
multiples_of_5 = np.arange(0, 101, 5)
print(multiples_of_5)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [20]:
#Find the maximum and minimum value in an array

In [21]:
arr = np.array([12, 45, 7, 89, 23])
print("Maximum:", arr.max())
print("Minimum:", arr.min())

Maximum: 89
Minimum: 7


In [22]:
#Find the index position of the largest element

In [23]:
arr = np.array([12, 45, 7, 89, 23])
index = arr.argmax()
print("Index of largest element:", index)

Index of largest element: 3


In [24]:
#Sort an array in ascending order

In [25]:
arr = np.array([45, 12, 89, 7, 23])
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 7 12 23 45 89]


In [26]:
#Reverse an array without using loops

In [27]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [28]:
#Perform element-wise addition of two arrays

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [30]:
#Perform subtraction, multiplication, and division on arrays

In [31]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [32]:
#Find the mean, median, and standard deviation of an array

In [33]:
arr = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


In [34]:
#Find the sum of all rows and columns in a matrix

In [35]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row_sum = matrix.sum(axis=1)
column_sum = matrix.sum(axis=0)
print("Row Sum:")
print(row_sum)
print("Column Sum:")
print(column_sum)

Row Sum:
[ 6 15 24]
Column Sum:
[12 15 18]


In [36]:
#Multiply two matrices using NumPy

In [37]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])
matrix2 = np.array([
    [5, 6],
    [7, 8]
])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [38]:
#Find the transpose of a matrix

In [39]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
transpose = matrix.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
#Find the determinant of a matrix

In [41]:
matrix = np.array([
    [1, 2],
    [3, 4]
])
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

Determinant: -2.0000000000000004
